// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeletekstBotHangfire.Data;

#nullable disable

namespace TeletekstBotHangfire.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241117093012_AddLastPageChangesToTeletekstPages")]
    partial class AddLastPageChangesToTeletekstPages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeletekstBotHangfire.Models.Ef.TeletekstPage", b =>
                {
                    b.Property<int>("PageNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PageNr"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("LastPageChanges")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastUpdatedInDbAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Screenshot")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("PageNr");

                    b.ToTable("TeletekstPages");
                });
#pragma warning restore 612, 618
        }
    }
}
